// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IcomPinia: typeof import('./components/icons/IcomPinia.vue')['default']
    IconMoon: typeof import('./components/icons/IconMoon.vue')['default']
    NavLinks: typeof import('./components/NavLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsInfo: typeof import('./components/SettingsInfo.vue')['default']
    UploadFile: typeof import('./components/UploadFile.vue')['default']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
  }
}
